

class LocaleText {


  static Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'Get Started':'Get Started',
      'name': 'name',
      'email':'email',
      'Your picture': 'Your picture',
      'My list':'My list',
      'Everyone':'Everyone',
      'Favorites':'Favorites',
      'My Chats':'My Chats',
      'viewes':'viewes',
      'requests':'Requests',
      'dates':'Dates',
      'Compare':'Compare',
      'Compare To':'Compare To',
      'Contacted me about':'Contacted me about',
      'Required fields':'Required fields',
      'Male':'Male',
      'Female':'Female',
      'First name':'First name',
      'Last name':'Last name',
      'Date of Birth':'Date of Birth',
      'Area':'Area',

      'Status':'Status',
      'Religious':'Religious',
      'Hashkafa':'Hashkafa',
      'Eda':'Eda',
      'Smoking':'Smoking',
      'About them short':'About them short',
      'About them long':'About them long',
      'Height':'Height',

      'First name is required':'First name is required',
      'Last name is required':'Last name is required',
      'Date of Birth is required':'Date of Birth is required',
      'Area is required':'Area is required',
      'Status is required':'Status is required',
      'Religious is required':'Religious is required',
      'Hashkafa is required':'Hashkafa is required',
      'Eda is required':'Eda is required',
      'Smoking is required':'Smoking is required',
      'About them short is required':'About them short is required',
      'About them long is required':'About them long is required',
      'Height is required':'Height is required',
      'Not a valid date':'Not a valid date',
      'Add at least one image!':'Add at least one image!',
      'What are they looking for?':'What are they looking for?',
      'More info':'More info',
      'Sherut':'Sherut',
      'This field is required':'This field is required',
      'choose date':'choose date',
      'Plony':'Plony',
      'Almony':'Almony',
      'm':'m',
      'Please enter a valid date':'Please enter a valid date',
      'Add a candidate':'Add a candidate',
      'Form is not valid!  Please review and correct!':'Form is not valid!  Please review and correct!',
      'Age':'Age',
      'Who am I':'Who am I',
      'What am I looking for':'hat am I looking for',
      'Status':'Status',
      'Hashkafa':'Hashkafa',
      'Height':'Height',
      'Religious':'Religious',
      'Smoking':'Smoking',
      'Eda':'Eda',
      'Search Name':'Search Name',
      'Country':'Country'
    },
    'he': {
      'name': 'שם',
      'email':'אימייל',
      'Your picture': 'התמונה שלך',
      'Get Started':'התחל',
      'My list':'שלי',
      'Everyone':'כולם',
      'Favorites':'מועדפים',
      'My Chats':"צ'אט",
      'viewes':'צפיות',
      'requests':'בקשות',
      'dates':'פגישות',
      'Compare':'השווה',
      'Compare To':'השווה ל',
      'Contacted me about':'יצר איתי קשר על',
      'Required fields':'שדות חובה',
      'Male':'זכר',
      'Female':'נקבה',
      'First name':'שם פרטי',
      'Last name':'שם משפחה',
      'Date of Birth':'תאריך לידה',
      'Area':'אזור',
      'Sherut':'שירות',
      'm':"מ'",
      'Status':'סטטוט',
      'Religious':'רמה דתית',
      'Hashkafa':'השקפה',
      'Eda':'עדה',
      'Smoking':'עישון',
      'About them short':'על המועמד במשפט',
      'About them long':'על המועמד ארוך',
      'Height':'גובה',

      'First name is required':'נדרש שם פרטי',
      'Last name is required':'נדרש שם משפחה',
      'Date of Birth is required':'נדרש תאריך לידה',
      'Area is required':'נדרש איזור',
      'Status is required':'נדרש סטטוס',
      'Religious is required':'נדרש רמה דתית',
      'Hashkafa is required':'נדרש השקפה',
      'Eda is required':'נדרש עדה',
      'Smoking is required':'נדרש עישון',
      'About them short is required':'About them short is required',
      'About them long is required':'About them long is required',
      'Height is required':'Height is required',
      'Not a valid date':'תאריך לא חוקי',
      'Add at least one image!':'צריך לפחות תמונה אחת',
      'What are they looking for?':'מה הם מחפשים?',
      'More info':'מידע נוסף',
      'This field is required':'זהו שדה חובה',
      'Add a candidate':'הוסף מועמד',
      'Plony':'פלוני',
      'Almony':'אלמוני',
      'Please enter a valid date':'מעל גיל 18...',
      'Form is not valid!  Please review and correct!':'הטופס אינו תקף! אנא עיין ותקן. ',
      'choose date':'בחר תאריך',
      'Age':'גיל',
      'Who am I':'מי אני',
      'What am I looking for':'מי אני מחפש',
      'Status':'סטטוס',
      'Hashkafa':'השקפה',
      'Height':'גובה',
      'Smoking':'עישון',
      'Eda':'עדה',
      'Search Name':'חפש שם',
      'Country':'ארץ'
    },
  };

  static String getLocaleText(languageCode,text) {
    return _localizedValues[languageCode][text];
  }
}